const SET_TABLE_LOADING: string = "SET_TABLE_LOADING",
  FETCH_EXPERIMENTS: string = "FETCH_EXPERIMENTS",
  SET_EXPERIMENTS_TO_STORE: string = "SET_EXPERIMENTS_TO_STORE",
  UPDATE_SEARCH: string = "UPDATE_SEARCH",
  SET_UPDATED_EXPERIMENT_TO_STORE: string = "SET_UPDATED_EXPERIMENT_TO_STORE",
  SET_CURRENT_EXPERIMENT: string = "SET_CURRENT_EXPERIMENT",
  SET_EXPERIMENT_NAME: string = "SET_EXPERIMENT_NAME",
  START_EDIT_NAME: string = "START_EDIT_NAME",
  CLEAR_UNDO_CHANGE_EXPERIMENT_NAME: string =
    "CLEAR_UNDO_CHANGE_EXPERIMENT_NAME",
  SAVE_NEW_EXPERIMENT_NAME: string = "SAVE_NEW_EXPERIMENT_NAME",
  CLEAR_CURRENT_EXPERIMENT: string = "CLEAR_CURRENT_EXPERIMENT",
  SET_SAVE_NAME_LOADING: string = "SET_SAVE_NAME_LOADING";

export default {
  SET_TABLE_LOADING,
  SET_EXPERIMENTS_TO_STORE,
  UPDATE_SEARCH,
  FETCH_EXPERIMENTS,
  SET_UPDATED_EXPERIMENT_TO_STORE,
  SET_CURRENT_EXPERIMENT,
  SET_EXPERIMENT_NAME,
  START_EDIT_NAME,
  CLEAR_UNDO_CHANGE_EXPERIMENT_NAME,
  SAVE_NEW_EXPERIMENT_NAME,
  SET_SAVE_NAME_LOADING,
  CLEAR_CURRENT_EXPERIMENT,
};
